export const meetingsStats = [
  { label: "اجتماعات قادمة", value: 4 },
  { label: "اجتماعات هذا الشهر", value: 9 },
  { label: "محاضر قيد الإعداد", value: 2 },
  { label: "قرارات تحتاج متابعة", value: 12 },
  { label: "مهام متأخرة", value: 5 },
  { label: "متوسط الحضور", value: "82%" },
  { label: "دعوات غير مؤكدة", value: 7 },
  { label: "اجتماعات مؤرشفة", value: 32 },
];

export const meetingsAlerts = [
  { message: "اجتماع المدربين غداً الساعة 18:00 — 3 دعوات لم تُؤكَّد بعد.", type: "warning" },
  { message: "محضر اجتماع المكتب التنفيذي بتاريخ 10/07/2026 في انتظار الاعتماد.", type: "info" },
];

export const clubMeetingsList = [
  {
    id: "m1",
    title: "اجتماع المدربين الأسبوعي",
    type: "اجتماع فني",
    branch: "كرة القدم",
    team: "أقل من 17",
    organizer: "المدير الرياضي",
    date: "2026-07-18",
    startTime: "18:00",
    endTime: "19:30",
    place: "قاعة الاجتماعات",
    mode: "حضوري",
    priority: "عادي",
    status: "مجدول",
    invited: 14,
    confirmed: 11,
    attendance: "—",
  },
  {
    id: "m2",
    title: "اجتماع المكتب التنفيذي الداخلي",
    type: "اجتماع المكتب التنفيذي",
    branch: "إداري",
    team: "—",
    organizer: "الأمين العام",
    date: "2026-07-15",
    startTime: "19:30",
    endTime: "21:00",
    place: "قاعة الاجتماعات",
    mode: "حضوري",
    priority: "مهم",
    status: "جاري",
    invited: 11,
    confirmed: 10,
    attendance: "9/11",
  },
  {
    id: "m3",
    title: "اجتماع مسؤولي الفروع",
    type: "اجتماع مسؤولي الفروع",
    branch: "جميع الفروع",
    team: "—",
    organizer: "نائب الرئيس",
    date: "2026-07-12",
    startTime: "17:00",
    endTime: "18:30",
    place: "قاعة الاجتماعات",
    mode: "مختلط",
    priority: "مهم",
    status: "في انتظار المحضر",
    invited: 8,
    confirmed: 8,
    attendance: "8/8",
  },
  {
    id: "m4",
    title: "اجتماع أولياء الأمور — فئة أقل من 14",
    type: "اجتماع أولياء الأمور",
    branch: "الجودو",
    team: "أقل من 14",
    organizer: "مسؤول الفريق",
    date: "2026-07-22",
    startTime: "18:30",
    endTime: "20:00",
    place: "قاعة المحاضرات",
    mode: "حضوري",
    priority: "عادي",
    status: "الدعوات مرسلة",
    invited: 32,
    confirmed: 24,
    attendance: "—",
  },
  {
    id: "m5",
    title: "اجتماع تحضيري — بطولة داخلية",
    type: "اجتماع تحضيري",
    branch: "كرة اليد",
    team: "ناشئين",
    organizer: "مدرب الفريق",
    date: "2026-07-10",
    startTime: "16:00",
    endTime: "17:00",
    place: "قاعة مغطاة",
    mode: "حضوري",
    priority: "عاجل",
    status: "معتمد",
    invited: 18,
    confirmed: 17,
    attendance: "16/18",
  },
];

export const meetingDecisions = [
  {
    number: "قرار 12/2026",
    meeting: "اجتماع المكتب التنفيذي",
    title: "شراء معدات تدريب إضافية للفئة الشبانية",
    type: "مالي",
    responsible: "مسؤول التجهيزات",
    deadline: "2026-10-20",
    status: "قيد التنفيذ",
  },
  {
    number: "قرار 11/2026",
    meeting: "اجتماع المدربين",
    title: "تعديل توقيت تدريب فئة أقل من 14 سنة",
    type: "فني",
    responsible: "مدرب كرة القدم",
    deadline: "2026-07-20",
    status: "مكتمل",
  },
  {
    number: "قرار 10/2026",
    meeting: "اجتماع مسؤولي الفروع",
    title: "تنظيم بطولة داخلية في نوفمبر",
    type: "تنظيمي",
    responsible: "المدير الرياضي",
    deadline: "2026-11-01",
    status: "قيد التنفيذ",
  },
  {
    number: "قرار 09/2026",
    meeting: "اجتماع إداري",
    title: "تحديث قائمة الاشتراكات المتأخرة",
    type: "إداري",
    responsible: "أمين المال",
    deadline: "2026-07-08",
    status: "متأخر",
  },
];

export const meetingTasks = [
  {
    task: "إعداد برنامج تدريبي جديد",
    responsible: "المدرب الرئيسي",
    deadline: "2026-07-15",
    status: "قيد التنفيذ",
    progress: "60%",
  },
  {
    task: "جرد معدات فريق كرة اليد",
    responsible: "مسؤول التجهيزات",
    deadline: "2026-07-18",
    status: "جديد",
    progress: "0%",
  },
  {
    task: "إرسال دعوات أولياء الأمور",
    responsible: "مسؤول الإدارة",
    deadline: "2026-07-14",
    status: "مكتمل",
    progress: "100%",
  },
  {
    task: "إعداد تقرير البطولة الداخلية",
    responsible: "مسؤول الإعلام",
    deadline: "2026-07-12",
    status: "متأخر",
    progress: "40%",
  },
];

export const meetingMinutes = [
  {
    number: "محضر 08/2026",
    title: "اجتماع المكتب التنفيذي — يوليو",
    date: "2026-07-10",
    author: "الأمين العام",
    status: "قيد المراجعة",
  },
  {
    number: "محضر 07/2026",
    title: "اجتماع المدربين — الأسبوع 2",
    date: "2026-07-05",
    author: "المدير الرياضي",
    status: "معتمد",
  },
];

export const meetingInvitations = [
  {
    meeting: "اجتماع المدربين الأسبوعي",
    invitee: "مدرب كرة القدم",
    sent: "2026-07-14",
    response: "أكد الحضور",
    status: "مؤكدة",
  },
  {
    meeting: "اجتماع المدربين الأسبوعي",
    invitee: "مدرب كرة اليد",
    sent: "2026-07-14",
    response: "لم يرد",
    status: "في الانتظار",
  },
  {
    meeting: "اجتماع أولياء الأمور",
    invitee: "ولي أمر — أحمد ب.",
    sent: "2026-07-13",
    response: "أكد الحضور",
    status: "مؤكدة",
  },
  {
    meeting: "اجتماع المكتب التنفيذي",
    invitee: "أمين المال",
    sent: "2026-07-12",
    response: "اعتذر",
    status: "مرفوض",
  },
];

export const meetingTypes = [
  { type: "اجتماع المكتب التنفيذي", goal: "مناقشة تسيير النادي واتخاذ قرارات داخلية" },
  { type: "اجتماع إداري", goal: "متابعة الملفات، الاشتراكات، التجهيزات والتنظيم" },
  { type: "اجتماع فني", goal: "مناقشة برامج التدريب والفرق والرياضيين" },
  { type: "اجتماع المدربين", goal: "تنسيق الحصص، الفئات، التقييمات والبرامج" },
  { type: "اجتماع مسؤولي الفروع", goal: "متابعة كل فرع رياضي داخل النادي" },
  { type: "اجتماع الفريق", goal: "توجيهات للاعبين قبل نشاط معين" },
  { type: "اجتماع أولياء الأمور", goal: "عرض البرنامج، الحضور، الاشتراكات والتوجيهات" },
  { type: "اجتماع طارئ", goal: "معالجة أمر عاجل داخل النادي" },
];
